# Generated by Django 4.1.7 on 2023-03-13 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="main",
            name="subtitle",
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
