# Generated by Django 4.1.7 on 2023-03-15 01:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Main",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="main/images/")),
                ("description", models.TextField(blank=True)),
                ("subtitle", models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("subtitle", models.CharField(blank=True, max_length=300)),
                ("main_image", models.ImageField(upload_to="main/images/")),
                (
                    "second_image",
                    models.ImageField(blank=True, upload_to="main/images/"),
                ),
                (
                    "third_image",
                    models.ImageField(blank=True, upload_to="main/images/"),
                ),
                ("description", models.TextField()),
                ("url", models.URLField(blank=True)),
            ],
        ),
    ]
