# Generated by Django 4.1.7 on 2023-03-22 04:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0002_document"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="pdf",
            field=models.FileField(upload_to="static/"),
        ),
    ]
