# Generated by Django 4.1.7 on 2023-03-22 04:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0003_alter_document_pdf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="main",
            name="description",
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="main",
            name="name",
            field=ckeditor.fields.RichTextField(max_length=100),
        ),
        migrations.AlterField(
            model_name="main",
            name="subtitle",
            field=ckeditor.fields.RichTextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="description",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="subtitle",
            field=ckeditor.fields.RichTextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="title",
            field=ckeditor.fields.RichTextField(max_length=100),
        ),
    ]
