# Generated by Django 4.1.7 on 2023-03-22 04:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0004_alter_main_description_alter_main_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolio",
            name="subtitle",
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
