# Generated by Django 4.1.7 on 2023-03-22 05:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0006_alter_portfolio_subtitle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolio",
            name="subtitle",
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="title",
            field=models.TextField(max_length=100),
        ),
    ]
