# Generated by Django 4.1.7 on 2023-03-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0007_alter_portfolio_subtitle_alter_portfolio_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="title",
        ),
        migrations.AlterField(
            model_name="document",
            name="pdf",
            field=models.FileField(upload_to="media/cv/"),
        ),
    ]
